-- CampusCycle PostgreSQL schema for Neon/PostgreSQL 15+
-- Run this file while connected to the target Neon database.

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    college         VARCHAR(150) NOT NULL,
    department      VARCHAR(100),
    semester        VARCHAR(20),
    hostel          VARCHAR(100),
    phone           VARCHAR(15),
    role            VARCHAR(20) NOT NULL DEFAULT 'STUDENT' CHECK (role IN ('STUDENT', 'ADMIN')),
    verified        BOOLEAN NOT NULL DEFAULT FALSE,
    suspended       BOOLEAN NOT NULL DEFAULT FALSE,
    rating_avg      NUMERIC(3,2) NOT NULL DEFAULT 0.00,
    rating_count    INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    parent_id   INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    icon        VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS listings (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id     INTEGER NOT NULL REFERENCES categories(id),
    title           VARCHAR(200) NOT NULL,
    description     TEXT NOT NULL,
    listing_type    VARCHAR(20) NOT NULL CHECK (listing_type IN ('SELL', 'BUY_REQUEST', 'BARTER', 'DONATE')),
    condition_type  VARCHAR(20) NOT NULL DEFAULT 'GOOD' CHECK (condition_type IN ('NEW', 'LIKE_NEW', 'GOOD', 'FAIR', 'POOR')),
    price           NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    barter_wanted   TEXT,
    pickup_location VARCHAR(200),
    course          VARCHAR(100),
    semester_tag    VARCHAR(20),
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIVE', 'SOLD', 'EXCHANGED', 'DONATED', 'REJECTED', 'REMOVED')),
    views           INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listing_images (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    image_path  VARCHAR(500) NOT NULL,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS wishlist (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlist UNIQUE (user_id, listing_id)
);

CREATE TABLE IF NOT EXISTS offers (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    buyer_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    offer_price     NUMERIC(10,2),
    exchange_note   TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS barter_proposals (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposer_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_listing_id   INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    offered_listing_id  INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    message             TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED')),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_requests (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seller_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message      TEXT,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS donation_requests (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id   INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    requester_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message      TEXT,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED')),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id        INTEGER REFERENCES listings(id) ON DELETE SET NULL,
    reported_user_id  INTEGER REFERENCES users(id) ON DELETE SET NULL,
    reason            VARCHAR(30) NOT NULL CHECK (reason IN ('FAKE_PRODUCT', 'SPAM', 'MISLEADING', 'INAPPROPRIATE', 'OTHER')),
    description       TEXT,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED')),
    admin_note        TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at       TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reviewed_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    listing_id      INTEGER REFERENCES listings(id) ON DELETE SET NULL,
    communication   SMALLINT NOT NULL CHECK (communication BETWEEN 1 AND 5),
    product_quality SMALLINT NOT NULL CHECK (product_quality BETWEEN 1 AND 5),
    trustworthiness SMALLINT NOT NULL CHECK (trustworthiness BETWEEN 1 AND 5),
    comment         TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id       INTEGER NOT NULL REFERENCES listings(id),
    seller_id        INTEGER NOT NULL REFERENCES users(id),
    buyer_id         INTEGER NOT NULL REFERENCES users(id),
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('SALE', 'BARTER', 'DONATION')),
    amount           NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    barter_id        INTEGER REFERENCES barter_proposals(id) ON DELETE SET NULL,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(100) NOT NULL UNIQUE,
    expires_at  TIMESTAMP NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_listings_status_created ON listings(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_listings_category ON listings(category_id);
CREATE INDEX IF NOT EXISTS idx_listing_images_listing ON listing_images(listing_id, is_primary DESC);
CREATE INDEX IF NOT EXISTS idx_chat_requests_users ON chat_requests(requester_id, seller_id);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_valid ON password_reset_tokens(token, used, expires_at);

INSERT INTO categories (name, parent_id, icon)
SELECT v.name, v.parent_id, v.icon
FROM (VALUES
    ('Academic', NULL::INTEGER, 'book'), ('Textbooks', 1, 'book-open'), ('Notes', 1, 'file-text'),
    ('Lab Manuals', 1, 'flask'), ('Previous Year Papers', 1, 'archive'), ('Calculators', 1, 'calculator'),
    ('Electronics', NULL::INTEGER, 'cpu'), ('Laptop', 7, 'laptop'), ('Monitor', 7, 'monitor'),
    ('Keyboard', 7, 'keyboard'), ('Mouse', 7, 'mouse'), ('Tablets', 7, 'tablet'),
    ('Chargers', 7, 'plug'), ('Earphones', 7, 'headphones'), ('Hostel Life', NULL::INTEGER, 'home'),
    ('Chair', 15, 'armchair'), ('Mattress', 15, 'bed'), ('Study Table', 15, 'table'),
    ('Fan', 15, 'wind'), ('Bucket', 15, 'bucket'), ('Hangers', 15, 'hanger'),
    ('Storage Boxes', 15, 'box'), ('Lifestyle', NULL::INTEGER, 'heart'), ('Bicycle', 23, 'bike'),
    ('Sports Equipment', 23, 'dumbbell'), ('Musical Instruments', 23, 'music'), ('Clothing', 23, 'shirt'),
    ('Bags', 23, 'briefcase'), ('Services', NULL::INTEGER, 'users'), ('Roommate Finder', 29, 'user-plus'),
    ('Tutor Finder', 29, 'graduation-cap'), ('Project Team Requests', 29, 'users-cog')
) AS v(name, parent_id, icon)
WHERE NOT EXISTS (SELECT 1 FROM categories);

INSERT INTO users (name, email, password_hash, college, department, role, verified)
SELECT 'Campus Admin', 'admin@college.edu',
       '$2a$10$9lrpsZb7CwNq0PC.xG9UlOM8KuzBT0XyEHpebpZHBV1flipfksIZi',
       'CampusCycle University', 'Administration', 'ADMIN', TRUE
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@college.edu');
